# create a docker image with mysql and a default password of admin

name: typehero

services:
  db:
    image: bitnami/mysql:latest
    container_name: typehero-db
    restart: always
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: typehero
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    # create a volume for the docker container_name
    volumes:
      - typehero-data:/bitnami/mysql/data
    ports:
      - 3306:3306
volumes:
  typehero-data:
    driver: local
